In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os
os.getcwd()

'C:\\Users\\Ajay\\Documents'

In [3]:
os.chdir("C:\\Users\\Ajay\Documents\\Python class")

In [91]:
train = pd.read_csv("train_ctrUa4K.csv")

In [144]:
test = pd.read_csv("test_lAUu6dG.csv")

In [93]:
train.head(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   
6  LP001013   Male     Yes          0  Not Graduate            No   
7  LP001014   Male     Yes         3+      Graduate            No   
8  LP001018   Male     Yes          2      Graduate            No   
9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [94]:
train.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [95]:
train.shape

(614, 13)

In [96]:
train.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [97]:
x = pd.DataFrame()
y = pd.DataFrame()

In [98]:
x = train.drop(['Loan_ID','Loan_Status'],axis=1)

In [99]:
y["Loan_Status"] = train["Loan_Status"]

In [100]:
x.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area  
0         Urban  
1         Rural  
2         Urban  
3         Urban  
4         Urban

In [101]:
y.head()

Loan_Status
0           Y
1           N
2           Y
3           Y
4           Y

In [102]:
x.isna().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
dtype: int64

In [103]:
x.groupby("Married").size()

Married
No     213
Yes    398
dtype: int64

In [104]:
x.groupby("Property_Area").size()

Property_Area
Rural        179
Semiurban    233
Urban        202
dtype: int64

In [105]:
x.groupby("Gender").size()

Gender
Female    112
Male      489
dtype: int64

In [106]:
x.groupby("Self_Employed").size()

Self_Employed
No     500
Yes     82
dtype: int64

In [107]:
x.groupby("Dependents").size()

Dependents
0     345
1     102
2     101
3+     51
dtype: int64

In [108]:
x.groupby("Credit_History").size()  

Credit_History
0.0     89
1.0    475
dtype: int64

In [109]:
x['Dependents'] = x.Dependents.replace(to_replace='3+',value='3')

In [110]:
x['Gender'] = x['Gender'].fillna('Male')
x['Married'] = x['Married'].fillna('Yes')
x['Self_Employed'] = x['Self_Employed'].fillna('No')
x['Dependents'] = x['Dependents'].fillna('0')
x['LoanAmount'] = x['LoanAmount'].fillna(x.LoanAmount.median())
x['Loan_Amount_Term'] = x['Loan_Amount_Term'].fillna(x.Loan_Amount_Term.median())
x['Credit_History'] = x['Credit_History'].fillna(1.0)

In [111]:
x.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  614.000000        614.000000   
mean       5403.459283        1621.245798  145.752443        342.410423   
std        6109.041673        2926.248369   84.107233         64.428629   
min         150.000000           0.000000    9.000000         12.000000   
25%        2877.500000           0.000000  100.250000        360.000000   
50%        3812.500000        1188.500000  128.000000        360.000000   
75%        5795.000000        2297.250000  164.750000        360.000000   
max       81000.000000       41667.000000  700.000000        480.000000   

       Credit_History  
count      614.000000  
mean         0.855049  
std          0.352339  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [112]:
x.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [113]:
x.head(10)

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   
5   Male     Yes          2      Graduate           Yes             5417   
6   Male     Yes          0  Not Graduate            No             2333   
7   Male     Yes          3      Graduate            No             3036   
8   Male     Yes          2      Graduate            No             4006   
9   Male     Yes          1      Graduate            No            12841   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       128.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   
5             4196.0       267.0             360.0             1.0   
6             1516.0        95.0             360.0             1.0   
7             2504.0       158.0             360.0             0.0   
8             1526.0       168.0             360.0             1.0   
9            10968.0       349.0             360.0             1.0   

  Property_Area  
0         Urban  
1         Rural  
2         Urban  
3         Urban  
4         Urban  
5         Urban  
6         Urban  
7     Semiurban  
8         Urban  
9     Semiurban

In [114]:
x = pd.get_dummies(x)

In [115]:
x.head(10)

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0       128.0             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History  Gender_Female  Gender_Male  Married_No  Married_Yes  \
0             1.0              0            1           1            0   
1             1.0              0            1           0            1   
2             1.0              0            1           0            1   
3             1.0              0            1           0            1   
4             1.0              0            1           1            0   
5             1.0              0            1           0            1   
6             1.0              0            1           0            1   
7             0.0              0            1           0            1   
8             1.0              0            1           0            1   
9             1.0              0            1           0            1   

   Dependents_0  Dependents_1  Dependents_2  Dependents_3  Education_Graduate  \
0             1             0             0             0                   1   
1             0             1             0             0                   1   
2             1             0             0             0                   1   
3             1             0             0             0                   0   
4             1             0             0             0                   1   
5             0             0             1             0                   1   
6             1             0             0             0                   0   
7             0             0             0             1                   1   
8             0             0             1             0                   1   
9             0             1             0             0                   1   

   Education_Not Graduate  Self_Employed_No  Self_Employed_Yes  \
0                       0                 1                  0   
1                       0                 1                  0   
2                       0                 0                  1   
3                       1                 1                  0   
4                       0                 1                  0   
5                       0                 0                  1   
6                       1                 1                  0   
7                       0                 1                  0   
8                       0                 1                  0   
9                       0                 1                  0   

   Property_Area_Rural  Property_Area_Semiurban  Property_Area_Urban  
0                    0                        0                    1  
1                    1                        0                    0  
2                    0                        0                    1  
3                    0                        0                    1  
4                    0                        0                    1  
5                    0                        0                    1  
6                    0                        0                    1  
7                    0                        1                    0  
8                    0                        0                    1  
9                    0                        1                    0

In [116]:
del x['Gender_Female']
del x['Married_No']
del x['Dependents_0']
del x['Education_Not Graduate']
del x['Self_Employed_No']
del x['Property_Area_Rural']

In [117]:
x.head(20)

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0              5849                0.0       128.0             360.0   
1              4583             1508.0       128.0             360.0   
2              3000                0.0        66.0             360.0   
3              2583             2358.0       120.0             360.0   
4              6000                0.0       141.0             360.0   
5              5417             4196.0       267.0             360.0   
6              2333             1516.0        95.0             360.0   
7              3036             2504.0       158.0             360.0   
8              4006             1526.0       168.0             360.0   
9             12841            10968.0       349.0             360.0   
10             3200              700.0        70.0             360.0   
11             2500             1840.0       109.0             360.0   
12             3073             8106.0       200.0             360.0   
13             1853             2840.0       114.0             360.0   
14             1299             1086.0        17.0             120.0   
15             4950                0.0       125.0             360.0   
16             3596                0.0       100.0             240.0   
17             3510                0.0        76.0             360.0   
18             4887                0.0       133.0             360.0   
19             2600             3500.0       115.0             360.0   

    Credit_History  Gender_Male  Married_Yes  Dependents_1  Dependents_2  \
0              1.0            1            0             0             0   
1              1.0            1            1             1             0   
2              1.0            1            1             0             0   
3              1.0            1            1             0             0   
4              1.0            1            0             0             0   
5              1.0            1            1             0             1   
6              1.0            1            1             0             0   
7              0.0            1            1             0             0   
8              1.0            1            1             0             1   
9              1.0            1            1             1             0   
10             1.0            1            1             0             1   
11             1.0            1            1             0             1   
12             1.0            1            1             0             1   
13             1.0            1            0             0             0   
14             1.0            1            1             0             1   
15             1.0            1            0             0             0   
16             1.0            1            0             1             0   
17             0.0            0            0             0             0   
18             1.0            1            1             0             0   
19             1.0            1            1             0             0   

    Dependents_3  Education_Graduate  Self_Employed_Yes  \
0              0                   1                  0   
1              0                   1                  0   
2              0                   1                  1   
3              0                   0                  0   
4              0                   1                  0   
5              0                   1                  1   
6              0                   0                  0   
7              1                   1                  0   
8              0                   1                  0   
9              0                   1                  0   
10             0                   1                  0   
11             0                   1                  0   
12             0                   1                  0   
13             0                   1                  0   
14       

In [118]:
from sklearn.preprocessing import StandardScaler
x = StandardScaler().fit_transform(x)

In [119]:
x

array([[ 0.07299082, -0.55448733, -0.21124125, ..., -0.39260074,
        -0.7820157 ,  1.42814704],
       [-0.13441195, -0.03873155, -0.21124125, ..., -0.39260074,
        -0.7820157 , -0.70020801],
       [-0.39374734, -0.55448733, -0.94899647, ...,  2.54711697,
        -0.7820157 ,  1.42814704],
       ...,
       [ 0.43717437, -0.47240418,  1.27616847, ..., -0.39260074,
        -0.7820157 ,  1.42814704],
       [ 0.35706382, -0.55448733,  0.49081614, ..., -0.39260074,
        -0.7820157 ,  1.42814704],
       [-0.13441195, -0.55448733, -0.15174486, ...,  2.54711697,
         1.2787467 , -0.70020801]])

In [120]:
y = y.values

In [121]:
from sklearn.linear_model import LogisticRegression
Reg = LogisticRegression().fit(x,y)

C:\Users\Ajay\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [122]:
train_pred = Reg.predict(x)

In [123]:
from sklearn.metrics import confusion_matrix

In [124]:
confusion_matrix(y,train_pred)

array([[ 84, 108],
       [  7, 415]], dtype=int64)

In [125]:
(415+84)/(415+84+108+7)

0.8127035830618893

In [126]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = 'entropy')
classifier_dt.fit(x,y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [127]:
train_pred = classifier_dt.predict(x)

In [128]:
confusion_matrix(y,train_pred)

array([[192,   0],
       [  0, 422]], dtype=int64)

In [149]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')
classifier_rf.fit(x,y)

C:\Users\Ajay\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [150]:
train_pred = classifier_rf.predict(x)

In [151]:
confusion_matrix(y,train_pred)

array([[190,   2],
       [  4, 418]], dtype=int64)

In [208]:
classifier_rf = RandomForestClassifier(n_estimators = 500, criterion = 'gini')
classifier_rf.fit(x,y)

C:\Users\Ajay\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [209]:
train_pred = classifier_rf.predict(x)

In [210]:
confusion_matrix(y,train_pred)

array([[192,   0],
       [  0, 422]], dtype=int64)

In [152]:
from sklearn.naive_bayes import GaussianNB
classifier_nvt = GaussianNB()
classifier_nvt.fit(x,y)

C:\Users\Ajay\anaconda3\lib\site-packages\sklearn\naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [153]:
train_pred = classifier_nvt.predict(x)

In [154]:
confusion_matrix(y,train_pred)

array([[ 87, 105],
       [ 18, 404]], dtype=int64)

In [156]:
from sklearn.ensemble import BaggingClassifier
classifier_bagging = BaggingClassifier(n_estimators=500, max_samples=1.0)
classifier_bagging.fit(x, y)

C:\Users\Ajay\anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:645: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=None, bootstrap=True, bootstrap_features=False,
                  max_features=1.0, max_samples=1.0, n_estimators=500,
                  n_jobs=None, oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [157]:
train_pred = classifier_bagging.predict(x)

In [158]:
confusion_matrix(y,train_pred)

array([[192,   0],
       [  0, 422]], dtype=int64)

In [225]:
from xgboost import XGBClassifier
classifier_xgb = XGBClassifier()
classifier_xgb.fit(x, y)

ModuleNotFoundError: No module named 'xgboost'

In [ ]:
train_pred = classifier_xgb.predict(x)

In [ ]:
confusion_matrix(y,train_pred)

In [164]:
test.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [165]:
test.isna().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [166]:
test.shape

(367, 12)

In [167]:
0.2*367

73.4

In [211]:
test = test.drop('Loan_ID',axis=1)

In [212]:
test['Gender'] = test['Gender'].fillna('Male')
test['Self_Employed'] = test['Self_Employed'].fillna('No')
test['Dependents'] = test['Dependents'].fillna('0')
test['LoanAmount'] = test['LoanAmount'].fillna(test.LoanAmount.median())
test['Loan_Amount_Term'] = test['Loan_Amount_Term'].fillna(test.Loan_Amount_Term.median())
test['Credit_History'] = test['Credit_History'].fillna(1.0)

In [213]:
test.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [214]:
test = pd.get_dummies(test)

In [215]:
del test['Gender_Female']
del test['Married_No']
del test['Dependents_0']
del test['Education_Not Graduate']
del test['Self_Employed_No']
del test['Property_Area_Rural']

In [216]:
from sklearn.preprocessing import StandardScaler
test = StandardScaler().fit_transform(test)

In [217]:
y_pred = classifier_rf.predict(test)

In [218]:
df = pd.DataFrame(data=y_pred,columns=['Loan_Status'])

In [219]:
Final = pd.DataFrame()

In [220]:
test = pd.read_csv("test_lAUu6dG.csv")

In [221]:
Final['Loan_ID'] = test['Loan_ID']
Final['Loan_Status'] = df['Loan_Status']

In [222]:
Final.head(10)

Loan_ID Loan_Status
0  LP001015           Y
1  LP001022           Y
2  LP001031           Y
3  LP001035           Y
4  LP001051           Y
5  LP001054           Y
6  LP001055           Y
7  LP001056           N
8  LP001059           Y
9  LP001067           Y

In [223]:
Final.to_csv(r'C:\Users\Ajay\Documents\outRf500.csv',index=False)